USE [master]
GO
/****** Object:  Database [Todo]    Script Date: 10/2/2014 10:48:55 AM ******/
CREATE DATABASE [Todo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Todo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Todo.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Todo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Todo_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Todo] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Todo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Todo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Todo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Todo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Todo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Todo] SET ARITHABORT OFF 
GO
ALTER DATABASE [Todo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Todo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Todo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Todo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Todo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Todo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Todo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Todo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Todo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Todo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Todo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Todo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Todo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Todo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Todo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Todo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Todo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Todo] SET RECOVERY FULL 
GO
ALTER DATABASE [Todo] SET  MULTI_USER 
GO
ALTER DATABASE [Todo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Todo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Todo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Todo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Todo] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Todo', N'ON'
GO
USE [Todo]
GO
/****** Object:  Table [dbo].[Todo]    Script Date: 10/2/2014 10:48:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Todo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](100) NOT NULL,
	[Completed] [bit] NOT NULL,
	[Order] [int] NOT NULL,
 CONSTRAINT [PK_Todo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [Todo] SET  READ_WRITE 
GO
